// ft232h_avalon_sys_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module ft232h_avalon_sys_mm_interconnect_2 (
		input  wire        pll_outclk0_clk,                       //                     pll_outclk0.clk
		input  wire        dma_reset_reset_bridge_in_reset_reset, // dma_reset_reset_bridge_in_reset.reset
		input  wire [17:0] dma_read_master_address,               //                 dma_read_master.address
		output wire        dma_read_master_waitrequest,           //                                .waitrequest
		input  wire        dma_read_master_chipselect,            //                                .chipselect
		input  wire        dma_read_master_read,                  //                                .read
		output wire [31:0] dma_read_master_readdata,              //                                .readdata
		output wire        dma_read_master_readdatavalid,         //                                .readdatavalid
		output wire [10:0] dma_ram_s2_address,                    //                      dma_ram_s2.address
		output wire        dma_ram_s2_write,                      //                                .write
		input  wire [31:0] dma_ram_s2_readdata,                   //                                .readdata
		output wire [31:0] dma_ram_s2_writedata,                  //                                .writedata
		output wire [3:0]  dma_ram_s2_byteenable,                 //                                .byteenable
		output wire        dma_ram_s2_chipselect,                 //                                .chipselect
		output wire        dma_ram_s2_clken                       //                                .clken
	);

	wire         dma_read_master_translator_avalon_universal_master_0_waitrequest;   // dma_ram_s2_translator:uav_waitrequest -> dma_read_master_translator:uav_waitrequest
	wire  [31:0] dma_read_master_translator_avalon_universal_master_0_readdata;      // dma_ram_s2_translator:uav_readdata -> dma_read_master_translator:uav_readdata
	wire         dma_read_master_translator_avalon_universal_master_0_debugaccess;   // dma_read_master_translator:uav_debugaccess -> dma_ram_s2_translator:uav_debugaccess
	wire  [17:0] dma_read_master_translator_avalon_universal_master_0_address;       // dma_read_master_translator:uav_address -> dma_ram_s2_translator:uav_address
	wire         dma_read_master_translator_avalon_universal_master_0_read;          // dma_read_master_translator:uav_read -> dma_ram_s2_translator:uav_read
	wire   [3:0] dma_read_master_translator_avalon_universal_master_0_byteenable;    // dma_read_master_translator:uav_byteenable -> dma_ram_s2_translator:uav_byteenable
	wire         dma_read_master_translator_avalon_universal_master_0_readdatavalid; // dma_ram_s2_translator:uav_readdatavalid -> dma_read_master_translator:uav_readdatavalid
	wire         dma_read_master_translator_avalon_universal_master_0_lock;          // dma_read_master_translator:uav_lock -> dma_ram_s2_translator:uav_lock
	wire         dma_read_master_translator_avalon_universal_master_0_write;         // dma_read_master_translator:uav_write -> dma_ram_s2_translator:uav_write
	wire  [31:0] dma_read_master_translator_avalon_universal_master_0_writedata;     // dma_read_master_translator:uav_writedata -> dma_ram_s2_translator:uav_writedata
	wire   [2:0] dma_read_master_translator_avalon_universal_master_0_burstcount;    // dma_read_master_translator:uav_burstcount -> dma_ram_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (18),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (18),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_read_master_translator (
		.clk                    (pll_outclk0_clk),                                                    //                       clk.clk
		.reset                  (dma_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (dma_read_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (dma_read_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (dma_read_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (dma_read_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (dma_read_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (dma_read_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (dma_read_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (dma_read_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (dma_read_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (dma_read_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (dma_read_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (dma_read_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (dma_read_master_waitrequest),                                        //                          .waitrequest
		.av_chipselect          (dma_read_master_chipselect),                                         //                          .chipselect
		.av_read                (dma_read_master_read),                                               //                          .read
		.av_readdata            (dma_read_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (dma_read_master_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                               //               (terminated)
		.av_byteenable          (4'b1111),                                                            //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_write               (1'b0),                                                               //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1),                                                               //               (terminated)
		.uav_response           (2'b00),                                                              //               (terminated)
		.av_response            (),                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (11),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (18),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) dma_ram_s2_translator (
		.clk                    (pll_outclk0_clk),                                                    //                      clk.clk
		.reset                  (dma_reset_reset_bridge_in_reset_reset),                              //                    reset.reset
		.uav_address            (dma_read_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (dma_read_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (dma_read_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (dma_read_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (dma_read_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (dma_read_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (dma_read_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (dma_read_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (dma_read_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (dma_read_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (dma_read_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (dma_ram_s2_address),                                                 //      avalon_anti_slave_0.address
		.av_write               (dma_ram_s2_write),                                                   //                         .write
		.av_readdata            (dma_ram_s2_readdata),                                                //                         .readdata
		.av_writedata           (dma_ram_s2_writedata),                                               //                         .writedata
		.av_byteenable          (dma_ram_s2_byteenable),                                              //                         .byteenable
		.av_chipselect          (dma_ram_s2_chipselect),                                              //                         .chipselect
		.av_clken               (dma_ram_s2_clken),                                                   //                         .clken
		.av_read                (),                                                                   //              (terminated)
		.av_begintransfer       (),                                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                                   //              (terminated)
		.av_burstcount          (),                                                                   //              (terminated)
		.av_readdatavalid       (1'b0),                                                               //              (terminated)
		.av_waitrequest         (1'b0),                                                               //              (terminated)
		.av_writebyteenable     (),                                                                   //              (terminated)
		.av_lock                (),                                                                   //              (terminated)
		.uav_clken              (1'b0),                                                               //              (terminated)
		.av_debugaccess         (),                                                                   //              (terminated)
		.av_outputenable        (),                                                                   //              (terminated)
		.uav_response           (),                                                                   //              (terminated)
		.av_response            (2'b00),                                                              //              (terminated)
		.uav_writeresponsevalid (),                                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                //              (terminated)
	);

endmodule
