# TCL File Generated by Component Editor 9.1sp2
# Tue Mar 15 10:04:05 EET 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | usb_ft2232 "usb_ft2232" v1.0
# | Darius Grigaitis 2011 2011.03.15.10:04:05
# | USB 2.0 FT2232 2011
# | 
# | E:/work/TOPAS/USB_test/usb_ft2232.vhd
# | 
# |    ./usb_ft2232.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module usb_ft2232
# | 
set_module_property DESCRIPTION "USB 2.0 FT2232 2011"
set_module_property NAME usb_ft2232
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP USB
set_module_property AUTHOR "Darius Grigaitis 2011"
set_module_property DISPLAY_NAME usb_ft2232
set_module_property TOP_LEVEL_HDL_FILE usb_ft2232.vhd
set_module_property TOP_LEVEL_HDL_MODULE usb_ft2232
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file usb_ft2232.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter TX_BUFFER INTEGER 512
set_parameter_property TX_BUFFER DEFAULT_VALUE 512
set_parameter_property TX_BUFFER DISPLAY_NAME TX_BUFFER
set_parameter_property TX_BUFFER UNITS None
set_parameter_property TX_BUFFER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TX_BUFFER DISPLAY_HINT ""
set_parameter_property TX_BUFFER AFFECTS_GENERATION false
set_parameter_property TX_BUFFER HDL_PARAMETER true
add_parameter USED_SIZE INTEGER 8
set_parameter_property USED_SIZE DEFAULT_VALUE 8
set_parameter_property USED_SIZE DISPLAY_NAME USED_SIZE
set_parameter_property USED_SIZE UNITS None
set_parameter_property USED_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USED_SIZE DISPLAY_HINT ""
set_parameter_property USED_SIZE AFFECTS_GENERATION false
set_parameter_property USED_SIZE HDL_PARAMETER true
add_parameter RX_BUFFER INTEGER 512
set_parameter_property RX_BUFFER DEFAULT_VALUE 512
set_parameter_property RX_BUFFER DISPLAY_NAME RX_BUFFER
set_parameter_property RX_BUFFER UNITS None
set_parameter_property RX_BUFFER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RX_BUFFER DISPLAY_HINT ""
set_parameter_property RX_BUFFER AFFECTS_GENERATION false
set_parameter_property RX_BUFFER HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 associatedClock clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 chipselect_n chipselect_n Input 1
add_interface_port avalon_slave_0 address address Input 5
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end usb_rd_n export Output 1
add_interface_port conduit_end usb_wr_n export Output 1
add_interface_port conduit_end usb_oe_n export Output 1
add_interface_port conduit_end usb_rxf_n export Input 1
add_interface_port conduit_end usb_txe_n export Input 1
add_interface_port conduit_end usb_data export Bidir 8
add_interface_port conduit_end usb_clock export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------
