	ft232h_avalon_sys u0 (
		.clk_clk                                    (<connected-to-clk_clk>),                                    //              clk.clk
		.clk_0_clk                                  (<connected-to-clk_0_clk>),                                  //            clk_0.clk
		.ddr3_pll_sharing_pll_mem_clk               (<connected-to-ddr3_pll_sharing_pll_mem_clk>),               // ddr3_pll_sharing.pll_mem_clk
		.ddr3_pll_sharing_pll_write_clk             (<connected-to-ddr3_pll_sharing_pll_write_clk>),             //                 .pll_write_clk
		.ddr3_pll_sharing_pll_locked                (<connected-to-ddr3_pll_sharing_pll_locked>),                //                 .pll_locked
		.ddr3_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-ddr3_pll_sharing_pll_write_clk_pre_phy_clk>), //                 .pll_write_clk_pre_phy_clk
		.ddr3_pll_sharing_pll_addr_cmd_clk          (<connected-to-ddr3_pll_sharing_pll_addr_cmd_clk>),          //                 .pll_addr_cmd_clk
		.ddr3_pll_sharing_pll_avl_clk               (<connected-to-ddr3_pll_sharing_pll_avl_clk>),               //                 .pll_avl_clk
		.ddr3_pll_sharing_pll_config_clk            (<connected-to-ddr3_pll_sharing_pll_config_clk>),            //                 .pll_config_clk
		.ddr3_pll_sharing_pll_mem_phy_clk           (<connected-to-ddr3_pll_sharing_pll_mem_phy_clk>),           //                 .pll_mem_phy_clk
		.ddr3_pll_sharing_afi_phy_clk               (<connected-to-ddr3_pll_sharing_afi_phy_clk>),               //                 .afi_phy_clk
		.ddr3_pll_sharing_pll_avl_phy_clk           (<connected-to-ddr3_pll_sharing_pll_avl_phy_clk>),           //                 .pll_avl_phy_clk
		.ddr3_status_local_init_done                (<connected-to-ddr3_status_local_init_done>),                //      ddr3_status.local_init_done
		.ddr3_status_local_cal_success              (<connected-to-ddr3_status_local_cal_success>),              //                 .local_cal_success
		.ddr3_status_local_cal_fail                 (<connected-to-ddr3_status_local_cal_fail>),                 //                 .local_cal_fail
		.ft232_usb_usb_data                         (<connected-to-ft232_usb_usb_data>),                         //        ft232_usb.usb_data
		.ft232_usb_usb_oe_n                         (<connected-to-ft232_usb_usb_oe_n>),                         //                 .usb_oe_n
		.ft232_usb_usb_rd_n                         (<connected-to-ft232_usb_usb_rd_n>),                         //                 .usb_rd_n
		.ft232_usb_usb_rxf_n                        (<connected-to-ft232_usb_usb_rxf_n>),                        //                 .usb_rxf_n
		.ft232_usb_usb_siwu                         (<connected-to-ft232_usb_usb_siwu>),                         //                 .usb_siwu
		.ft232_usb_usb_txe_n                        (<connected-to-ft232_usb_usb_txe_n>),                        //                 .usb_txe_n
		.ft232_usb_usb_wr_n                         (<connected-to-ft232_usb_usb_wr_n>),                         //                 .usb_wr_n
		.ft232_usb_usb_clock                        (<connected-to-ft232_usb_usb_clock>),                        //                 .usb_clock
		.memory_mem_a                               (<connected-to-memory_mem_a>),                               //           memory.mem_a
		.memory_mem_ba                              (<connected-to-memory_mem_ba>),                              //                 .mem_ba
		.memory_mem_ck                              (<connected-to-memory_mem_ck>),                              //                 .mem_ck
		.memory_mem_ck_n                            (<connected-to-memory_mem_ck_n>),                            //                 .mem_ck_n
		.memory_mem_cke                             (<connected-to-memory_mem_cke>),                             //                 .mem_cke
		.memory_mem_cs_n                            (<connected-to-memory_mem_cs_n>),                            //                 .mem_cs_n
		.memory_mem_dm                              (<connected-to-memory_mem_dm>),                              //                 .mem_dm
		.memory_mem_ras_n                           (<connected-to-memory_mem_ras_n>),                           //                 .mem_ras_n
		.memory_mem_cas_n                           (<connected-to-memory_mem_cas_n>),                           //                 .mem_cas_n
		.memory_mem_we_n                            (<connected-to-memory_mem_we_n>),                            //                 .mem_we_n
		.memory_mem_reset_n                         (<connected-to-memory_mem_reset_n>),                         //                 .mem_reset_n
		.memory_mem_dq                              (<connected-to-memory_mem_dq>),                              //                 .mem_dq
		.memory_mem_dqs                             (<connected-to-memory_mem_dqs>),                             //                 .mem_dqs
		.memory_mem_dqs_n                           (<connected-to-memory_mem_dqs_n>),                           //                 .mem_dqs_n
		.memory_mem_odt                             (<connected-to-memory_mem_odt>),                             //                 .mem_odt
		.oct_rzqin                                  (<connected-to-oct_rzqin>),                                  //              oct.rzqin
		.reset_reset_n                              (<connected-to-reset_reset_n>)                               //            reset.reset_n
	);

